{% set name = "VStrains" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/metagentools/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

build:
  number: 0
  skip: True  # [win]
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip>=22.3.1
    - python=3
    - graph-tool>=2.45
    - minimap2>=2.24
    - numpy>=1.23.5
    - gfapy>=1.2.3
    - matplotlib>=3.6.2
  run:
    - python=3
    - graph-tool>=2.45
    - minimap2>=2.24
    - numpy>=1.23.5
    - gfapy>=1.2.3
    - matplotlib>=3.6.2

test:
  commands:
    - vstrains -h

about:
  home: "https://github.com/metagentools/VStrains"
  license: MIT
  license_file: LICENSE
  summary: "VStrains: De Novo Reconstruction of Viral Strains via Iterative Path Extraction From Assembly Graphs"
  doc_url: "https://github.com/metagentools/VStrains/blob/master/README.md"
  dev_url: "https://github.com/metagentools/VStrains"

extra:
  recipe-maintainers:
    - RunpengLuo
  # identifiers:
  #   - doi:10.1101/2022.10.21.513181v3